name: Idris2 Build & Deploy

on:
  push:
    branches: [ "main" ]
    paths:
      - "**.idr"
      - "package.json"
      - "**.html"
      - "**.css"
      - "**.ipkg"
      - ".github/**"

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Install Idris 2 & Pack
        run: |
          sudo apt-get update
          sudo apt-get install -y chezscheme
          echo "chezscheme" | bash -c "$(curl -fsSL https://raw.githubusercontent.com/stefan-hoeck/idris2-pack/main/install.bash)"
          echo "$HOME/.pack/bin" >> $GITHUB_PATH
      - name: Verify Idris 2 Installation
        run: idris2 --version
      - name: Run Tests
        run: bun run test

      - name: Build REPL Executable
        run: |
          bun run build
          mv ./repl/build/exec/Repl ./repl/build/exec/Repl.js

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: repl-executable
          path: ./repl/build/exec/Repl.js

      - name: Build Web Artifacts
        run: bun run build:web

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: webpage
          build_dir: web/dist
          fqdn: https://dc.hotaru.icu
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
